name: Linux build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  TARGETS: KuzbassEngine

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v4
    
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          # Vulkan dependencies
          sudo apt-get install -y libvulkan-dev vulkan-validationlayers mesa-vulkan-drivers
    
      - name: Install Conan
        run: |
          pip install conan
          conan --version
    
      - name: Configure Conan profile
        run: |
          conan profile detect --force
          # Редактируем профиль через sed
          sed -i 's/compiler.cppstd=gnu17/compiler.cppstd=20/' /home/runner/.conan2/profiles/default
          sed -i 's/build_type=Release/build_type=${{matrix.configuration}}/' /home/runner/.conan2/profiles/default
          # Меняем версию компилятора на 11
          sed -i 's/compiler.version=13/compiler.version=11/' /home/runner/.conan2/profiles/default
          # Меняем libcxx если нужно
          # sed -i 's/compiler.libcxx=libstdc++/compiler.libcxx=libstdc++11/' /home/runner/.conan2/profiles/default
          # cat /home/runner/.conan2/profiles/default
    
      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing \
          -s os=Linux \
          -s arch=x86_64 \
          -s compiler=gcc \
          -s compiler.version=11 \
          -s compiler.libcxx=libstdc++ \
          -s compiler.cppstd=20 \
          -s build_type=${{matrix.configuration}}

      - name: Configure CMake
        run: |
          cmake --preset conan-default
    
      - name: Build
        run: |
          cmake --build build --config ${{matrix.configuration}} -v --target ${{env.TARGETS}}
    
      - name: Archive Artifacts
        run: |
          mkdir -p artifacts
          find build -name "${{env.TARGETS}}" -type f -exec cp {} artifacts/ \;
          zip -r artifacts-${{matrix.configuration}}.zip artifacts/
    
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts-${{matrix.configuration}}
          path: artifacts-${{matrix.configuration}}.zip