name: Linux build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  TARGETS: KuzbassEngine

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v4
    
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          # Для Vulkan (если нужно)
          sudo apt-get install -y libvulkan-dev vulkan-validationlayers mesa-vulkan-drivers
    
      - name: Install Conan
        run: |
          pip install conan
          conan --version
    
      - name: Configure Conan profile
        run: |
          conan profile detect --force
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.version=11 default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile update settings.build_type=${{matrix.configuration}} default
    
      - name: Install dependencies with Conan
        run: |
          conan install . --build=missing -s build_type=${{matrix.configuration}}
    
      - name: Configure CMake
        run: |
          cmake --preset conan-default -DCMAKE_BUILD_TYPE=${{matrix.configuration}}
    
      - name: Build
        run: |
          cmake --build build --config ${{matrix.configuration}} -v --target ${{env.TARGETS}}
    
      - name: Archive Artifacts
        run: |
          mkdir -p artifacts
          find build -name "${{env.TARGETS}}" -type f -exec cp {} artifacts/ \;
          zip -r artifacts-${{matrix.configuration}}.zip artifacts/
    
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts-${{matrix.configuration}}
          path: artifacts-${{matrix.configuration}}.zip