name: Windows build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  TARGETS: KuzbassEngine
  TEST_TARGET: KuzbassEngineTests

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        configuration:
          - Release
          - Debug

    steps:
      - uses: actions/checkout@v4

   
      - name: Install Conan
        run: pip install conan

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}}

      - name: Build Engine
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}} -v --target ${{env.TARGETS}}

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}} -v --target ${{env.TEST_TARGET}}

      - name: Run Tests (Debug only)
        if: matrix.configuration == 'Debug'
        run: ${{github.workspace}}/build/bin/${{matrix.configuration}}/${{env.TEST_TARGET}}.exe --gtest_output=xml:test-results.xml

      - name: Upload Test Results (Debug)
        if: matrix.configuration == 'Debug'
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-results
          path: test-results.xml

      - name: Publish Test Report (Debug)
        if: matrix.configuration == 'Debug'
        uses: phoenix-actions/test-reporting@v10
        with:
          name: Windows Test Results
          path: test-results.xml
          reporter: java-junit
          output-to: "step-summary"
          fail-on-error: "true"

      - name: Archive Artifacts
        run: Compress-Archive -Path build/bin/* -DestinationPath artifacts-${{matrix.configuration}}.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{matrix.configuration}}
          path: artifacts-${{matrix.configuration}}.zip
